FROM python:3.11.11-slim-bookworm 


WORKDIR /app


COPY requirements.txt /app

COPY app/data_process.py /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8501
  
CMD ["streamlit","run","data_process.py","--server.port=8501","--server.address=0.0.0.0"]

